### ISSUE TITLE
Allow to build/start specifc targets only

### ISSUE THREAD

**Issue by ZauberNerd** [untool/untool#331]
Add a CLI option to the `build` and `start` commands to build/start specific `targets` (`node`, `develop`, `graphql-mock-server` (as defined by Hops), `service-worker` (as defined by Hops)).

This would allow us to only start the GraphQL mock server in a Hops app, in order to have the server start without having to wait for the node and browser build to succeed when only the mock server is required.

**Comment by dmbch** [comment]
Due to the fact that that all the different builds work differently, this will get a bit messy (as discussed IRL). I would not mind if this was being tackled.

An alternative would be to add a specific command to only start that mock server in hops. If that is the primary/only use case, I would, in fact, prefer that approach.

**Comment by dmbch** [comment]
@ZauberNerd do you plan to follow up on this?

**Comment by dmbch** [comment]
Closing for now - please reopen if this is still required.
