### ISSUE TITLE
Should the doctor throw in production mode instead of printing warnings

### ISSUE THREAD

**Issue by ZauberNerd** [untool/untool#332]
This came up in a discussion with @skrings about quietly resuming erroneous operation in production mode or failing hard by throwing an exception.

**Comment by dmbch** [comment]
Since we always validate everything and some issues `untool` warns about are very much use-case specific, I would prefer not to throw exceptions if we do not have to.

E.g.: while I think it is valid to warn about a `serve` specific misconfiguration during a `build`, I do not think it is appropriate to throw, i.e. crash. In fact, I would prefer only crashing if absolutely necessary and recovering whenever possible.

If we do crash, however, I think we ought to provide as much context/info as possible, allowing our users to make a connection from crash to warning.

**Comment by ZauberNerd** [comment]
Fine for now. Maybe we can rethink this as part of Hops 12 / 13.
